

development:
  adapter: postgresql
  encoding: unicode
  database: zmartcase_development
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: Kth2015!

test:
  adapter: postgresql
  encoding: unicode
  database: zmartcase_test
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: Kth2015!